#!/usr/bin/env node
// Heuristic functions for Screeps strategic simulation.
// Trade exact per-creep simulation for ~95%-accurate aggregate math over 1000-2000 tick horizons.

export const TICK_LIFESPAN        = 1500;   // average creep lifespan ticks
export const SPAWN_TICKS_PER_PART = 3;      // 3 ticks to spawn one body part
export const HARVEST_PER_WORK     = 2;      // energy/tick per WORK part (harvest)
export const UPGRADE_PER_WORK     = 1;      // XP/tick per WORK part (upgrade)
export const SOURCE_REGEN_RATE    = 10;     // energy/tick per source (3000 / 300-tick cycle)
export const CONTAINER_DISTANCE   = 10;     // approx tiles: source → container → spawn

// Controller XP needed to go from RCL N → N+1
export const RCL_THRESHOLDS = [0, 200, 45000, 135000, 405000, 1215000, 3645000, 10935000, Infinity];

// Extensions unlocked at each RCL (cumulative count)
const EXTENSIONS_BY_RCL = [0, 0, 5, 10, 20, 30, 40, 50, 60];

export function extensionsAtRcl(rcl) {
  return EXTENSIONS_BY_RCL[Math.min(rcl, 8)] ?? 0;
}

export function energyCapForRcl(rcl) {
  return 300 + extensionsAtRcl(rcl) * 50;
}

// Typical body composition per role (mid-game, ~RCL2-3 budget)
export const ROLE_SPEC = {
  harvester: { parts: 5, workParts: 2, cost: 300 },
  hauler:    { parts: 4, carryParts: 2, carryCapacity: 100, cost: 200 },
  upgrader:  { parts: 3, workParts: 1, cost: 200 },
  builder:   { parts: 3, workParts: 1, cost: 200 },
  warrior:   { parts: 5, attackParts: 2, cost: 260 },
  scout:     { parts: 1, cost: 50 },
  scavenger: { parts: 3, carryParts: 2, cost: 150 },
};

// ─── Movement ────────────────────────────────────────────────────────────────

export function moveTicks(distance, hasRoads = false) {
  return Math.ceil(distance * (hasRoads ? 0.5 : 1.0));
}

// ─── Energy flow ─────────────────────────────────────────────────────────────

// Gross energy harvested per tick. With containers, harvesters park and harvest continuously.
export function energyIncome(harvesterCount, sourceCount, hasContainers) {
  if (!hasContainers) {
    return harvesterCount * HARVEST_PER_WORK; // no parking: roughly 1 WORK part effective
  }
  // 2 WORK parts × 2 e/part = 4 e/tick per harvester, capped by source regen
  const perHarvesterOutput = HARVEST_PER_WORK * 2;
  const activeHarvesters = Math.min(harvesterCount, sourceCount);
  return Math.min(sourceCount * SOURCE_REGEN_RATE, activeHarvesters * perHarvesterOutput);
}

// Energy delivered to spawn/storage by haulers per tick
export function haulerThroughput(haulerCount, containerDistance, hasRoads) {
  const carry = ROLE_SPEC.hauler.carryCapacity;
  const roundTrip = 2 * moveTicks(containerDistance, hasRoads);
  return (haulerCount * carry) / roundTrip;
}

// Energy consumed per tick by upgraders and builders
export function energyDrain(upgraderCount, builderCount, buildActive) {
  const upgradeCost = upgraderCount * UPGRADE_PER_WORK;
  const buildCost   = buildActive ? builderCount * 5 : 0; // 1 WORK × 5 build power
  return upgradeCost + buildCost;
}

// ─── Spawn ───────────────────────────────────────────────────────────────────

export function spawnTicksForRole(role) {
  return (ROLE_SPEC[role]?.parts ?? 3) * SPAWN_TICKS_PER_PART;
}

// ─── Combat ──────────────────────────────────────────────────────────────────

export function attackDPS(warriorCount) {
  return warriorCount * 60; // 2 ATTACK parts × 30 dmg = 60 per warrior
}

export function siegeViability(warriors, defenderHp = 20000) {
  const dps = attackDPS(warriors);
  return { viable: dps > 80, ttk: dps > 0 ? Math.ceil(defenderHp / dps) : Infinity };
}

// ─── State assessment ────────────────────────────────────────────────────────

export function detectBottleneck(s) {
  const containers  = s.structs?.containers ?? 0;
  const roads       = s.structs?.roads ?? 0;
  const income      = energyIncome(s.creeps?.harvester ?? 0, 2, containers > 0);
  const throughput  = haulerThroughput(s.creeps?.hauler ?? 0, CONTAINER_DISTANCE, roads > 4);
  if (income < 5)              return 'HARVESTER_SHORTAGE';
  if (throughput < income * 0.7) return 'HAULER_SHORTAGE';
  if (income >= SOURCE_REGEN_RATE * 2) return 'SOURCE_MAXED';
  return 'BALANCED';
}

export function evaluatePhase(s, currentPhase) {
  const warriors  = s.creeps?.warrior ?? 0;
  const fillRatio = (s.energy?.avail ?? 0) / (s.energy?.cap ?? 300);
  if (currentPhase === 'ECONOMY' && warriors >= 3 && fillRatio > 0.65) return 'ASSESS';
  if (currentPhase === 'ASSESS'  && warriors >= 5)                      return 'RUSH';
  if (currentPhase === 'ASSESS'  && fillRatio < 0.12)                   return 'ECONOMY';
  if (currentPhase === 'RUSH'    && warriors <= 1)                       return 'DEFEND';
  if (currentPhase === 'DEFEND'  && warriors >= 3)                       return 'ASSESS';
  return currentPhase;
}

// XP per tick generated by upgraders (1 WORK part = 1 XP/tick)
export function upgradeFlux(upgraderCount) {
  return upgraderCount * UPGRADE_PER_WORK;
}

// Build energy consumed per tick by builders (1 WORK part = 5 build power)
export function buildFlux(builderCount) {
  return builderCount * 5;
}

// Composite score for a finished simulation run (used for build-order ranking)
export function scoreRun(snapshots) {
  if (!snapshots.length) return 0;
  const last = snapshots.at(-1);

  // RCL progress: reward reaching higher RCL, bonus for being mid-level within it
  const rclScore = (last.rcl - 2) * 20 + (last.ctrl?.pct ?? 0) * 0.5;

  // Energy stability: fraction of ticks with energy > 25% capacity
  const stableCount = snapshots.filter(s => (s.energy?.avail ?? 0) > (s.energy?.cap ?? 300) * 0.25).length;
  const stabilityScore = stableCount / snapshots.length * 30;

  // Creep roster score: reward having a productive army
  const creeps = last.creeps ?? {};
  const rosterScore = Math.min(10, Object.values(creeps).reduce((a, b) => a + b, 0) * 0.5);

  return rclScore + stabilityScore + rosterScore;
}
